### ISSUE TITLE
Add support for custom-formatter

### ISSUE THREAD

**Issue by bram96** [Phillip9587/nx-stylelint#121]
We're using teamcity for CI and would like to use nx-stylelint to get it runing within the nx commands.

Could you please add support for the custom-formatter CLI flag?

**Comment by Phillip9587** [comment]
I'm sorry it took so long but custom Formatter Support has been released with [**nx-stylelint v13.2.0**](https://github.com/Phillip9587/nx-stylelint/releases/tag/v13.2.0)

Please take a look at https://github.com/Phillip9587/nx-stylelint#custom-formatters
