### ISSUE TITLE
ignorePattern should not be ["!**/*"]

### ISSUE THREAD

**Issue by criskrzysiu** [Phillip9587/nx-stylelint#169]
Hi, 
ignore pattern should be 
["!**/*.css"] or ["!**/*.css", "!**/*.scss"] if scss support added, because currently ide like webstorm try to stylelint files like html etc

**Comment by Phillip9587** [comment]
Hello @criskrzysiu,

The `ignorePatterns` are correct. You should specify which files you want to lint either through the [`lintFilePatterns` ](https://github.com/Phillip9587/nx-stylelint#lintfilepatterns) of the executor or through the glob patter if you use the Stylelint CLI directly.
