### ISSUE TITLE
v13.2.0 - 'config' is not found in schema

### ISSUE THREAD

**Issue by danr-za** [Phillip9587/nx-stylelint#205]
Running `nx run app:stylelint` throws the following error:

`'config' is not found in schema`

**Comment by Phillip9587** [comment]
@danr-za Please provide the Output of running `nx report` and your nx-stylelint version.

**Comment by Phillip9587** [comment]
@danr-za In version 13.2.0 of nx-stylelint the `config` option was renamed to `configFile`. But in a normal setup with the `.stylelintrc.json` file at the project root the `configFile` option must not be specified. If you have a `.stylelintrc.json` file at the project root, you can remove the `config`/`configFile` option from your `workspace.json`/`angular.json`/`project.json`.

**Comment by danr-za** [comment]
Hey @Phillip9587 
This is my `stylelintrc.json` at the root:
```json
{
  "extends": [
    "stylelint-config-standard-scss",
    "stylelint-config-idiomatic-order",
    "stylelint-config-prettier"
  ],
  "plugins": ["stylelint-scss"],
  "ignoreFiles": ["node_modules/**", "dist/**"],
  "rules": {
    "at-rule-no-unknown": null,
    "value-keyword-case": [
      "lower",
      {
        "camelCaseSvgKeywords": true
      }
    ],
    "value-no-vendor-prefix": [true, { "ignoreValues": ["box"] }],
    "scss/at-rule-no-unknown": [
      true,
      {
        "ignoreAtRules": [
          "tailwind",
          "apply",
          "variants",
          "responsive",
          "screen",
          "layer"
        ]
      }
    ],
    "selector-pseudo-class-no-unknown": [
      true,
      {
        "ignorePseudoClasses": ["global"]
      }
    ],
    "declaration-block-trailing-semicolon": null,
    "no-invalid-position-at-import-rule": [
      true,
      {
        "ignoreAtRules": ["tailwind"]
      }
    ],
    "no-descending-specificity": null,
    "order/properties-alphabetical-order": null
  },
  "syntax": "scss"
}

```

And Nx report:
```sh
  Node : 16.13.0
  OS   : darwin x64
  yarn : 3.1.0
  
  nx : 13.4.6
  @nrwl/angular : undefined
  @nrwl/cli : 13.4.6
  @nrwl/cypress : 13.4.6
  @nrwl/devkit : 13.4.6
  @nrwl/eslint-plugin-nx : 13.4.6
  @nrwl/express : undefined
  @nrwl/jest : 13.4.6
  @nrwl/linter : 13.4.6
  @nrwl/nest : undefined
  @nrwl/next : undefined
  @nrwl/node : 13.4.6
  @nrwl/nx-cloud : undefined
  @nrwl/react : 13.4.6
  @nrwl/react-native : undefined
  @nrwl/schematics : undefined
  @nrwl/tao : 13.4.6
  @nrwl/web : 13.4.6
  @nrwl/workspace : 13.4.6
  @nrwl/storybook : 13.4.6
  @nrwl/gatsby : undefined
  typescript : 4.5.5
  rxjs : 6.6.7
 ---------------------------------------
  Community plugins:
         nx-stylelint: 13.2.0

```

**Comment by Phillip9587** [comment]
@danr-za It looks like your stylelint config is from a old version of nx-stylelint/stylelint. 

Please run the following commands to update your configs and stylelint.

`npx nx migrate nx-stylelint@13.2.0 --from="nx-stylelint@12.0.0"`

A `migrations.json` file should be created. Then run the migrations with:

`npx nx migrate --run-migrations=migrations.json`

In general please update nx-stylelint with `npx nx migrate nx-stylelint` instead of just increasing the version. Major versions often contain breaking changes which need migrations to be resolved.

**Comment by danr-za** [comment]
Cool, didn't know the plugin had its own migrations as well.
Thanks @Phillip9587, solved 🚀 .
