### ISSUE TITLE
Question: custom rules in Nx repo?

### ISSUE THREAD

**Issue by dandean** [Phillip9587/nx-stylelint#309]
I'm still way finding here, but does this plugin provide the ability to write custom Stylelint rules as an Nx library? I'm trying to figure out how to do this without publishing a custom rule to npm.

**Comment by Phillip9587** [comment]
As I understand your question, you want to implement custom rules for a Nx Monorepo and use them only inside this monorepo?

It is possible to write your custom rules inside your Nx Monoprepo. You can follow the [guide ](https://stylelint.io/developer-guide/plugins) to write a plugin and import it in your stylelint config.
