### ISSUE TITLE
Package "nx-stylelint" was found but does not support schematics.

### ISSUE THREAD

**Issue by brunano21** [Phillip9587/nx-stylelint#32]
Hi,
first of all - many thanks for your package, it looks promising.

However, I have encountered an issue while creating the configuration for a given project.

When running `nx g nx-stylelint:configuration --project demo-app` this is the error that I get:

```
An unhandled exception occurred: Package "nx-stylelint" was found but does not support schematics.
See "C:\Users\User\AppData\Local\Temp\1\ng-0eRiyV\angular-errors.log" for further details.
```

Now, I have to tell you that I'm using nx v 9.1. Is nx-stylelint@12.0.0 compatible with that nx's version?

**Comment by Phillip9587** [comment]
@brunano21 nx-stylelint's major version number matches the version number of the nx packages. Nx introduces its @nrwl/devkit with version 11 of nx so the first supported version of nx is 11. I'm sorry!

**Comment by brunano21** [comment]
Ok Great, that was what I suspected :-) Many thanks for the response!
