### ISSUE TITLE
Support Stylelint 15

### ISSUE THREAD

**Issue by muuvmuuv** [Phillip9587/nx-stylelint#462]
It still works but dependency bump would be nice :)

![Bildschirm­foto 2023-02-16 um 13 17 39](https://user-images.githubusercontent.com/11534760/219362610-4339a8fa-2556-4719-bd3c-87dc37d98705.png)

Dependabot already got you covered I guess :D #457

**Comment by Phillip9587** [comment]
See https://github.com/Phillip9587/nx-stylelint/releases/tag/v15.0.0
