### ISSUE TITLE
Add TS and JS Support

### ISSUE THREAD

**Issue by christophbuehler** [Phillip9587/nx-stylelint#479]
Hi, Stylelint supports linting CSS / SCSS within TS and JS files. Would it be possible to either update the configuration generator to target files other than `.css` or create a new generator that adds JS and or TS files to the `lintFilePatterns`?

**Comment by Phillip9587** [comment]
It is possible to lint CSS and SCSS within TS and JS files. You just have to configure it yourself. 

1. Add the wanted file extensions to the `lintFilePatterns` inside of the `project.json` target configuration.
2. Configure your `.stylelintrc.json` file according to the [stylelint docs](https://stylelint.io/user-guide/get-started#using-more-than-one-custom-syntax)

I`m not planning to extend the configuration generator to support more file formats. But you can create your own local generator and extend the nx-stylelint configuration generator: 

- https://nx.dev/recipes/generators/local-generators
- https://nx.dev/recipes/generators/composing-generators

**Comment by christophbuehler** [comment]
Hi @Phillip9587 , thanks for the response. Although I think it would be a reasonable addition to the generator, I respect your decision. Have a good day!
