### ISSUE TITLE
Generate nx-stylelint for a application give error Expected argument `jsonString` to be a `string`, got `object`

### ISSUE THREAD

**Issue by ringodotnl** [Phillip9587/nx-stylelint#56]
Hello, 

Situation:
NX workspace is updated from 9.8.0 to 12.x. Added eslint and now added nx-stylelint.

Now trying to add styelint to a project with command: 
`ng generate nx-stylelint:configuration --project=my-app --skipFormat --no-interactive --dry-run` 
which resuilt in this error: Expected argument `jsonString` to be a `string`, got `object`

Any idea's how to solve that?

Cheers,
Ringo.

**Comment by Phillip9587** [comment]
Hi Ringo,

Please run `nx report` and provide the output. I will try to reproduce the issue when i get your version details. 

Thanks

**Comment by Phillip9587** [comment]
Please also provide the full stacktrace of the error.

**Comment by ild0tt0re** [comment]
Hi @Phillip9587 , 
    I have the same problem as @ringodotnl with **Nx 12**
    
**Report:**
```
  Node : 14.16.1
  OS   : darwin x64
  yarn : 1.22.10

  nx : 12.0.6
  @nrwl/angular : Not Found
  @nrwl/cli : 12.3.3
  @nrwl/cypress : 12.3.3
  @nrwl/devkit : 12.3.3
  @nrwl/eslint-plugin-nx : 12.3.3
  @nrwl/express : Not Found
  @nrwl/jest : 12.3.3
  @nrwl/linter : 12.3.3
  @nrwl/nest : Not Found
  @nrwl/next : 12.3.3
  @nrwl/node : 12.3.4
  @nrwl/react : 12.3.3
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.3.3
  @nrwl/web : 12.3.3
  @nrwl/workspace : 12.3.3
  @nrwl/storybook : 12.3.3
  @nrwl/gatsby : Not Found
  typescript : 4.2.4
``` 

how can I provide you a full stacktrace of the error?

Thanks!

**Comment by Phillip9587** [comment]
@ild0tt0re Please try updating your global Nx installation with `npm i -g nx@latest`.

**Comment by Phillip9587** [comment]
@ild0tt0re Please also provide your stylelint version.

**Comment by ild0tt0re** [comment]
> @ild0tt0re Please also provide your stylelint version.

All my stylelint stuff:
├─ nx-stylelint@12.0.0
├─ stylelint-config-recommended@5.0.0
├─ stylelint-config-styled-components@0.1.1
├─ stylelint-processor-styled-components@1.10.0
└─ stylelint@13.13.1

**Comment by cogoo** [comment]
I had the same issues with nx-stylelint@12.

nx-stylelint@11 seems to work for me

**Comment by Phillip9587** [comment]
@ringodotnl @ild0tt0re @cogoo Can someone please copy the full error message and details. 

I cannot reproduce the issue. I tested it on linux and windows but i have no mac to test on. I used the latest `create-nx-workspace` to generate a new Nx workspace and added `nx-stylelint`. The init and configuration generators worked.

**Comment by cogoo** [comment]
@Phillip9587 this was the full extent of the error message:

```
Expected argument jsonString to be a string, got object
```

I'll do some debugging later tonight and share my findings.

P.S Thanks for this Nx plugin, its awesome!

**Comment by Phillip9587** [comment]
I added e2e tests and a github workflow which runs the e2e test on linux, windows and mac on with node version 12, 14 and 16. I still don't get any errors while running the generators. 

I just released version 12.1.0 of nx-stylelint maybe you can try it out?

**Comment by cogoo** [comment]
Same error:

![Screenshot 2021-05-26 at 16 01 26](https://user-images.githubusercontent.com/14809642/119683592-ac6b6780-be3b-11eb-88c9-5c6f16b476d3.png)

Nx report: 

```
  Node : 12.22.1
  OS   : darwin x64
  npm  : 6.14.12
  
  nx : Not Found
  @nrwl/angular : 11.6.3
  @nrwl/cli : 11.6.3
  @nrwl/cypress : 11.6.3
  @nrwl/devkit : 11.6.3
  @nrwl/eslint-plugin-nx : 11.6.3
  @nrwl/express : Not Found
  @nrwl/jest : 11.6.3
  @nrwl/linter : 11.6.3
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.6.3
  @nrwl/web : Not Found
  @nrwl/workspace : 11.6.3
  @nrwl/storybook : 11.6.3
  @nrwl/gatsby : Not Found
  typescript : 4.0.7
```

**Comment by Phillip9587** [comment]
@cogoo Please use nx-stylelint 11 or update to Nx 12. nx-stylelint's major version has to match the major version of Nx. Thanks

**Comment by cogoo** [comment]
> @cogoo Please use nx-stylelint 11 or update to Nx 12. nx-stylelint's major version has to match the major version of Nx. Thanks

awesome, thanks thats what i observed. nx-stylelint 11 works on my repo

**Comment by Phillip9587** [comment]
@ild0tt0re Do you still have problems with nx-stylelint?

**Comment by ild0tt0re** [comment]
Fixed! Thanks!
