### ISSUE TITLE
Support for stylelint 16

### ISSUE THREAD

**Issue by Yberion** [Phillip9587/nx-stylelint#578]
Hello @Phillip9587,

Is there any plan to support `stylelint` `16` ?

It looks like the minimum version for `stylelint-config-standard` is `35.0.0`  if we use `stylelint` `16`.

- https://github.com/stylelint/stylelint/releases/tag/16.0.0
- https://github.com/stylelint/stylelint-config-standard/releases/tag/35.0.0

Have a good day.

**Comment by Phillip9587** [comment]
v17.1.0 with stylelint v16 support has been released: https://github.com/Phillip9587/nx-stylelint/releases/tag/v17.1.0

**Comment by Yberion** [comment]
Thank you!
