### ISSUE TITLE
Compatability with NX 18 and Stylelint 16

### ISSUE THREAD

**Issue by siiron** [Phillip9587/nx-stylelint#630]
Now that NX 18 is out, I'd love to see a new version of nx-stylelint with compatability with NX 18 and Stylelint 16.

**Comment by pvds** [comment]
@siiron with NX 18 compatibility do you also mean [Inferred tasks](https://nx.dev/concepts/inferred-tasks) support?

**Comment by siiron** [comment]
@pvds I haven't really considered that yet. I'm not using this feature in NX.

**Comment by pvds** [comment]
> @pvds I haven't really considered that yet. I'm not using this feature in NX.

It's part of NX project Crystal and to me seems the only part of NX 18 that nx-stylelint would have to be compatible with.
This could be considered as a separate issue from Stylelint 16 compatibility though.

**Comment by siiron** [comment]
@pvds I agree.

**Comment by Phillip9587** [comment]
@siiron @pvds nx-stylelint is compatible with Nx 18 and Stylelint 16. I will update the README to include the version in the compatibility table. 

@pvds Inferred tasks support will be in the next major

**Comment by Phillip9587** [comment]
I'm closing this issue as completed and open a new one for the inferred tasks support.
