### ISSUE TITLE
Stylelint in Nx Workspace 9.8.0 - Package "nx-stylelint" was found but does not support schematics

### ISSUE THREAD

**Issue by ringodotnl** [Phillip9587/nx-stylelint#69]
Q: Trying to use stylelint in Nx Workspace 9.8.0 with these steps:

- npm i -D nx-stylelint
- nx g nx-stylelint:configuration --project myapp

Results in:
An unhandled exception occurred: Package "nx-stylelint" was found but does not support schematics.

From which NX workspace version is nx-stylelint supported ?

Cheers,
Ringo.

**Comment by Phillip9587** [comment]
@ringodotnl I'm sorry. nx-stylelint`s major version number has to match the major version of Nx. So nx-stylelint it supported in Nx workspaces from version 11.

**Comment by Phillip9587** [comment]
@cogoo I will add schematics support for you. But @ringodotnl 's problem is related to his Nx version. I started rhe development of nx-stylelint while Nx 11 was the current version. I don't have enough time to support older versions of Nx.

**Comment by Phillip9587** [comment]
@cogoo Do you use nx-stylelint 11 or 12?

**Comment by cogoo** [comment]
@Phillip9587 currently on 11. Will be migrating to 12 hopefully this weekend 🙏🏾

**Comment by Phillip9587** [comment]
@cogoo I will add schematics support to nx-stylelint 12. But i definitly recommend using the `@nrwl/devkit` in Nx workspaces instead of the angular devkit.

**Comment by cogoo** [comment]
> @cogoo I will add schematics support to nx-stylelint 12. But i definitly recommend using the `@nrwl/devkit` in Nx workspaces instead of the angular devkit.

Thanks.

If I'm delayed in migrating to 12, I'll love to assist in creating a PR to add support for `v11` if possible

oo didn't even notice that, will look into the `@nrwl/devkit`

**Comment by Phillip9587** [comment]
@cogoo nx-stylelint 12.2.0 now supports schematics. If i have time left i will backport the changes to nx-stylelint 11.

**Comment by cogoo** [comment]
@Phillip9587 ❤️  thank you!
