### ISSUE TITLE
update readme

### ISSUE THREAD

**Issue by maxisam** [Phillip9587/nx-stylelint#70]
After running nx g nx-stylelint:configuration --project projectName for the first time, you still need to run another yarn or npm to pull stylelint-config-xxx libraries.

**Comment by Phillip9587** [comment]
@maxisam The install step should actually happen automatically. I will do some testing.

**Comment by Phillip9587** [comment]
@maxisam This was fixed and released in nx-stylelint [v12.1.1](https://github.com/Phillip9587/nx-stylelint/releases/tag/v12.1.1)
